import { Sora } from "next/font/google";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

const sora = Sora({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} dark:bg-body bg-[#1D1E28] font-[Sora] text-white`}
      >
        <Header />
        {children}
        <Footer />
        <div id="modal-root-portal"></div>
      </body>
    </html>
  );
}
